spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600

      routes:
        - id: THY-DATA-SERVICE-COMMAND
          uri: lb://THY-DATA-SERVICE
          predicates:
            - Path=/api/v1/location/**, /api/v1/transportation**
            - Method=POST, PUT, DELETE

        - id: THY-FLIGHT-MANAGEMENT-SERVICE
          uri: lb://THY-ROUTE-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/route/**
            - Method=GET

      discovery:
        locator:
          enabled: true

server:
  port: 8016

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8012/eureka}
  instance:
    prefer-ip-address: true