spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: THY-FLIGHT-MANAGEMENT-SERVICE
          uri: lb://THY-FLIGHT-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/**
      discovery:
        locator:
          enabled: true

server:
  port: 8016

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8012/eureka}
  instance:
    prefer-ip-address: true