spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # DATA SERVICE - Sizin paylaştığınız Controller buraya yönlenir
        - id: THY-DATA-SERVICE
          uri: lb://THY-DATA-SERVICE
          predicates:
            - Path=/api/v1/location/**, /api/v1/data/**

        # FLIGHT MANAGEMENT SERVICE
        - id: THY-FLIGHT-MANAGEMENT-SERVICE
          uri: lb://THY-FLIGHT-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/location/**, /api/v1/transportation/**
      discovery:
        locator:
          enabled: true

server:
  port: 8016

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8012/eureka}
  instance:
    prefer-ip-address: true