server:
  port: 8015
spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: thy-data

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8012/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}