spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: thy-flight-management-service
          uri: lb://thy-flight-management-service
          predicates:
            - Path=/api/v1/route/**
      discovery:
        locator:
          enabled: true

server:
  port: 8016

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8012/eureka}
  instance:
    prefer-ip-address: true